# Generated by Django 6.0.6 on 2026-06-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('ymm', 'Year/Make/Model'), ('vin', 'VIN')], max_length=10)),
                ('vin', models.CharField(blank=True, max_length=17, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('make', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('trim', models.CharField(blank=True, max_length=50, null=True)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Search Histories',
                'ordering': ['-searched_at'],
            },
        ),
    ]
